# va in html title
title: "Prossima Apertura"
# va in html meta description
description: A new model of urban regeneration
# va nella navigazione
sitename: Prossima Apertura
# accessibile con site.url
url: https://prossimaapertura.orizzontale.org

collections:
  - features
  - features_en

kramdown:
  hard_wrap: true
